### ISSUE TITLE
Problema ao mesclar tabelas relacionadas (chaves estrangeiras)

### ISSUE THREAD

**Issue by xshifty** [xshifty/my-php-merge#12]
@jackmakiyama e @vitorccsiqueira estou criando essa issue, para que possamos resolver juntos este problema.
Qualquer dúvida ou problema que tu encontrar, pode abrir uma issue aqui nesse repositório, que a gente resolve junto, beleza?

**Comment by jackmakiyama** [comment]
Blz, @xshifty !
Com certeza vou precisar implementar algo por aqui.

**Comment by ghost** [comment]
@xshifty blz agradeço Rafael! Você consegue encontrar um tempo qualquer dia desses, acho que 1h de conferência para navegarmos na ferramenta e no ponto onde está ocorrendo aquele probleminha com client_id e client_recommended_id para o @jackmakiyama analisar e conseguir prover uma solução. São apenas esses dois campos o problema mesmo, de resto está fluindo OK.

**Comment by jackmakiyama** [comment]
@xshifty analisando aqui, tenho algumas considerações.

O problema está acontecendo quando rola esse flat dos dados repetidos.
Os dados são descartados e os ids das chaves estrangeiras não são atualizados com o id que permaneceu.

@xshifty poderia sinalizar pra mim onde que acontece esse flat de dados no código?

**Comment by jackmakiyama** [comment]
@xshifty seria [aqui](https://github.com/xshifty/my-php-merge/blob/master/src/Actions/MoveMergeData.php#L91)?

**Comment by xshifty** [comment]
@jackmakiyama vou fechar pq vc ja resolveu

**Comment by jackmakiyama** [comment]
🍻
